sample_sheets:
  raw_data: custom.tsv
mode: custom 
msa_option: none
n_splits: 1 # Optional, for running using the 'parallel' branch of this repo. To maximize resources utilization, the value of this flag should correspond to min(number_of_predictions, number_of_multi-GPU_nodes). 
af3_flags:
  --af3_container: /gpfs/cssb/group/cssb-topf/natan/singularity_containers/alphafold3/alphafold3_parallel_a100_40gb_latest_template_free_.sif

run_data_pipeline_locally: true
exclusive_lock: true
